### ISSUE TITLE
Add Wallet Shortcut/Widget

### ISSUE THREAD

**Issue by yulose9** [ILIYANGERMANOV/ivy-wallet#1042]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to have a feature where you can easily access a wallet from the homescreen using a widget which when tapped will redirect you to that wallet on the app.

### Why do you need it?

- Because it is more convenient to tap a single icon widget on the homescreen rather than tapping 2-3 time on the app
- It makes easier transaction on a specific wallet

### How do you imagine it?

When tap and hold a specific wallet from the app it will show a submenu from where I tapped and hold which shows an option to "Create a widget on homescreen"

**Comment by ILIYANGERMANOV** [comment]
Hi @yulose9 , we have a Widget for adding transactions with 1-click and also app icon shortcuts - check them out and let us know if they do the work 👌
