### ISSUE TITLE
Hide Ivy Wallet preview in Recent Apps when "App Lock" is ON

### ISSUE THREAD

**Issue by ivywallet** [ILIYANGERMANOV/ivy-wallet#107]
You got Biometrics but my account is still exposed. People can see from the background my money.

Also:
- When "App Lock" is ON automatically navigate to authentication screen again after 5min of inactivity

**Comment by Vishwa-Raghavendra** [comment]
"I'm on it

**Comment by ILIYANGERMANOV** [comment]
Hi @Vishwa-Raghavendra thanks for your interest in contributing to Ivy Wallet! A bit clarification for this issue.

Only if "Lock App" is ON:
- the Ivy Wallet app content in "Recent" should be blurred/hidden
- in onResume() if the app was more than 5min in the background the user should be navigated to unlock the app with biometrics again

**Comment by ILIYANGERMANOV** [comment]
Closed by PR #125 thanks to @Vishwa-Raghavendra!
