### ISSUE TITLE
[BUG] calculator allows multiple decimal points

### ISSUE THREAD

**Issue by ryg-git** [ILIYANGERMANOV/ivy-wallet#1121]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### Describe the bug

when user tries to add a new transaction (income, expense or account transfer) the calculator allows multiple decimal points.

### To Reproduce

1. Add a new transaction either income or expense or account transfer.
2. Open calculator while entering amount.
3. User can add multiple decimal points in calculator.

### Expected behavior

Multiple decimal points shouldn't be allowed in the calculator

### Screenshots

![WhatsApp Image 2022-07-13 at 10 52 10 PM](https://user-images.githubusercontent.com/69393483/178793605-37cb56fd-d91a-48ca-91db-8cf974a1c5fa.jpeg)

### Smartphone

realme GT neo 2.

**Comment by ryg-git** [comment]
I would like to work on this issue

**Comment by ILIYANGERMANOV** [comment]
Just consider that some locales use "." for decimal separator and others ","
