### ISSUE TITLE
Adding different currencies within an account

### ISSUE THREAD

**Issue by Zewar-G** [ILIYANGERMANOV/ivy-wallet#116]
**What do you want to be added or improved?**
As a user I want to be able to add different currencies within one account

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
- [ ] Yes, it already exists.
- [x] No, it's a new issue.
- [ ] I'm not sure but I've checked.

_Put an `x` in the boxes that apply._

- [x] Demo: Checking checkbox using `[x]`

**Explain with bullets why do you need it**
- a_ in order to have over view on all the assets that I have from one place.

**Explain how do you imagine it in detail**
Write any implementation details that might help us better fulfill your feature request.
**I'd like to:**
- a_  for example i have bank account which has different currencies € $ £ so instead of having three different account,I'd like to have one account named bank and able to separate all of the three currencies.

**Comment by ILIYANGERMANOV** [comment]
Hi @Zewar-G that's good one. We'll address it in #110
