### ISSUE TITLE
Adding a photo of the receipt to the entry record

### ISSUE THREAD

**Issue by Zewar-G** [ILIYANGERMANOV/ivy-wallet#118]
**What do you want to be added or improved?**
As a user I want to take or attach a photo of the payment/ receipt

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
- [ ] Yes, it already exists.
- [x] No, it's a new issue.
- [ ] I'm not sure but I've checked.

_Put an `x` in the boxes that apply._

- [x] Demo: Checking checkbox using `[x]`

**Explain with bullets why do you need it**
- a_ in order to keep a track for future reference, or to be able to get to it back when needed.

**Explain how do you imagine it in detail**
Write any implementation details that might help us better fulfill your feature request.
**I'd like to:**
- a_ be able to attach the receipt to the entry via taking a photo or attaching an image from the phone itself.

**Comment by ILIYANGERMANOV** [comment]
Will be implemented in #6
