### ISSUE TITLE
[BUG] App not launching after Fresh Install

### ISSUE THREAD

**Issue by husseinaltaaf** [ILIYANGERMANOV/ivy-wallet#132]
**Describe the bug**
I just did a fresh installation in a new android and the app is totally blank white/black screen.

**To Reproduce**
1. Install the app from play store
2. Launch it

**Expected behavior**
It should launch the app's UI

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note 9
 - OS: Android 10

**Comment by ILIYANGERMANOV** [comment]
Hi @husseinaltaaf, thanks for reporting! We're currently deploying a hotfix release. Shame on us. It'll be live today! Aplogoies for the inconvenience. https://github.com/ILIYANGERMANOV/ivy-wallet/actions/runs/1466115073

**Comment by ILIYANGERMANOV** [comment]
Fixed by #133
