### ISSUE TITLE
[ICONS] Add support for more icons (and group them)

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [ILIYANGERMANOV/ivy-wallet#14]
Ivy Wallet can have more icons to better personalize your categories and icons. When having more icons it would be good to group them in logical categories.

**Comment by ILIYANGERMANOV** [comment]
User's feedback
- There Are No Icon For Petrol

**Comment by StarHamster** [comment]
@ILIYANGERMANOV, can we consider this issue solved?
