### ISSUE TITLE
Import CSV from BLUECOINS (com.rammigsoftware.bluecoins)

### ISSUE THREAD

**Issue by singhgautam7** [ILIYANGERMANOV/ivy-wallet#144]
**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**

- [ ] Yes
- [ ] No
- [ ] Kinda (please describe):

### Google PlayStore URL to the app from which you want to import:
- URL: https://play.google.com/store/apps/details?id=com.rammigsoftware.bluecoins

### Attach Samples CSV from the app:

Attach an exported CSV file from the app to this issue.

**CSV file requirements:**
- [ ] includes Income type transaction
- [ ] includes Expense type transaction
- [ ] includes Transfer type transaction (optional)
- [ ] includes title, description, all attributes available in the app (optional)

**Is CSV export from the app free?**

- [x] Yes
- [ ] No
- [ ] It depends (please describe):

_Put an `x` in the boxes that apply._

- [x] Demo: Checking checkbox using `[x]`

## Developer/Contributor Notes

- Checkout
  this **[Sample Commit](https://github.com/ILIYANGERMANOV/ivy-wallet/commit/323ed68343a0904ee33f226480716a30368fd646)**
  to see how import CSV works in Ivy Wallet
- Make sure that the imported dates of the transactions are correct

**Comment by ILIYANGERMANOV** [comment]
Hi @singhgautam7 would you give us a sample CSV? We'll implement an import from BLUECOINS :)
This closes #145

**Comment by ILIYANGERMANOV** [comment]
@singhgautam7 the CSV which you can provide us will require to have all transaction types as values in it. Otherwise, we can't implement a logic to import them properly.

**Comment by singhgautam7** [comment]
[bluecoins transactions_list_table.csv](https://github.com/ILIYANGERMANOV/ivy-wallet/files/7553480/bluecoins.transactions_list_table.csv)

This is the csv I exported from my bluecoins app.
