### ISSUE TITLE
[BUG] ... CSV import of the file failed I don't know the reason behind it.

### ISSUE THREAD

**Issue by singhgautam7** [ILIYANGERMANOV/ivy-wallet#145]
**Describe the bug**
Tried importing a file which I made myself for.importing the data at once, but it failed, and I don't know why it failed.

**Smartphone (please complete the following information):**
 - Device: OnePlus 7pro
 - OS: oxygen os with Android 11

![Screenshot_20211117-134948.jpg](https://user-images.githubusercontent.com/31505446/142162139-1f0c15b9-9824-422f-ad3b-9aaea06e9840.jpg)

**Comment by ILIYANGERMANOV** [comment]
Hi @singhgautam7 can you share a sample of your CSV file? Also from which did you export this file? Ivy Wallet support CSV import only in specific formats.

**Comment by ILIYANGERMANOV** [comment]
Import from BLUECOINS isn't supported => this isn't a bug. We'll support import from BLUECOINS in this #144 issue.

**Comment by singhgautam7** [comment]
[Ivy - ivy.csv](https://github.com/ILIYANGERMANOV/ivy-wallet/files/7553482/Ivy.-.ivy.csv)

This is the file I used to import in ivy wallet app.
I created this file myself, by taking data from bluecoins app. Can you tell me what wrong did I do here.

**Comment by ILIYANGERMANOV** [comment]
Hi @singhgautam7, great job on mapping the columns correctly! To make it work encode the file in Charsets.UTF_16 and it should work.

**Comment by singhgautam7** [comment]
Hi @ILIYANGERMANOV thank you for the suggestion. Do you happen to know a tool to convert it to utf16?

**Comment by ILIYANGERMANOV** [comment]
@singhgautam7 try this one - https://onlineutf8tools.com/convert-utf8-to-utf16

**Comment by singhgautam7** [comment]
[Ivy.csv](https://github.com/ILIYANGERMANOV/ivy-wallet/files/7554504/Ivy.csv)

**Comment by singhgautam7** [comment]
![Uploading Screenshot_20211117-174152.jpg…]()

**Comment by singhgautam7** [comment]
![Screenshot_20211117-174152.jpg](https://user-images.githubusercontent.com/31505446/142198585-affa76ae-bd23-460a-a036-f80c378bf438.jpg)

**Comment by ILIYANGERMANOV** [comment]
Hmm, I don't know. Better wait for the official support for import from BLUECOINS.

**Comment by singhgautam7** [comment]
That sounds cool :)
