### ISSUE TITLE
Change months in ItemStatistic screen with horizontal swipe

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [ILIYANGERMANOV/ivy-wallet#148]
**What do you want to be added or improved?**
As a user I want to change months in ItemStatisticScreen.kt with left and right swipe.

![Screenshot_20211117-175343_Ivy Wallet](https://user-images.githubusercontent.com/5564499/142235112-a438ddc3-9313-41e6-866d-4c2fe0a374b6.jpg)

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
- [ ] Yes, it already exists.
- [x] No, it's a new issue.
- [ ] I'm not sure but I've checked.

_Put an `x` in the boxes that apply._

- [x] Demo: Checking checkbox using `[x]`

**Explain with bullets why do you need it**
- convenience
- feels intuitive

**Explain how do you imagine it in detail**
Write any implementation details that might help us better fulfill your feature request.
**I'd like to:**
- swipe left => next month
- swipe right => previous month

Tips:
- re-use prev/next month logic from the screen
- re-use horizaontalSwipeListener()

**Comment by Vishwa-Raghavendra** [comment]
I am on it

**Comment by ILIYANGERMANOV** [comment]
Implemented by @Vishwa-Raghavendra. Thanks for the contribution!
