### ISSUE TITLE
Rework ItemStatistics scrolling

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [ILIYANGERMANOV/ivy-wallet#17]
![Screenshot_20211103-223922_Ivy Wallet](https://user-images.githubusercontent.com/5564499/140189204-0386aec6-9f5b-4be9-9d51-269faf6cca1e.jpg)

This screen scrolling UX is glitchy for everyone and terrible on small screens.

**Solution**
- Use standard scrolling instead of fancy animation.

**Comment by Vishwa-Raghavendra** [comment]
I am on it.
