### ISSUE TITLE
Open Home More menu with swipe down gesture

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [ILIYANGERMANOV/ivy-wallet#18]
**Problem**
To open Home More Menu you need to click the arrow down icon at the top of the screen which might be a bad experience if you're using a device with a large screen. 

**Solution**
To improve the UX we can implement a swipe-down gesture detection when the gesture is done in the upper half of the screen. => Open Home More Menu

![Screenshot_20211104-200209_Ivy Wallet](https://user-images.githubusercontent.com/5564499/140394551-8e1fe424-c281-401a-9926-83756c1dfd8a.jpg)

**Comment by timmyCoder** [comment]
i'm on it
