### ISSUE TITLE
Option to display transfers to excluded accounts as expense

### ISSUE THREAD

**Issue by ivywallet** [ILIYANGERMANOV/ivy-wallet#216]
E.g. I want to save some money, so I have a monthly transfer to an excluded account. It would make sense to add this to expenses, so I know I reached my savings goal of at the end of the month income=expense.

**Comment by ILIYANGERMANOV** [comment]
We'll develop a standalone "Savings" feature in the future which will help you achieve exactly this. Thanks for the suggestion!
