### ISSUE TITLE
 [BUG] Error When Import CSV from Money Manager By KTW. It Say "1 Row From CSV file Not Recognized"

### ISSUE THREAD

**Issue by ivywallet** [ILIYANGERMANOV/ivy-wallet#242]

**Comment by ILIYANGERMANOV** [comment]
That's expected. Not all rows can imported.

**Comment by vishwasnavadak** [comment]
When I am trying to import the data from Money Manager, it always errors with `100% failed, *** rows from csv file not recognized`.
