### ISSUE TITLE
Opening/Initial balance

### ISSUE THREAD

**Issue by ivywallet** [ILIYANGERMANOV/ivy-wallet#33]
I want to be able to set account's initial balance w/o having income transaction.

**Comment by ILIYANGERMANOV** [comment]
Hi, thank you for your feedback! This a good request. We've covered it in #3 so I'll close it as duplicate.

**Comment by Bibi2013** [comment]
How long does take to transfer fun from  ivy wallet  to PayPal

**Comment by Bibi2013** [comment]
How can I doing I'm new into this
