### ISSUE TITLE
Improve font styling

### ISSUE THREAD

**Issue by swapnilkadlag** [ILIYANGERMANOV/ivy-wallet#345]
**Is the project building?**
Yes

**What would you like to improve?**
I want to:
- Submit a PR to improve font/text styling

Because:
- I noticed that, since the app's raleway font's baseline isn't properly aligned, there are paddings being used in many places to achieve proper alignment.

How:
- We can use compose's baseline shifting to properly align our fonts.

Before using baseline shifting:
![before](https://user-images.githubusercontent.com/37185368/147803385-6f1f6698-c081-4cda-8f38-93853c607fe6.jpg)

After using baseline shifting:
![after](https://user-images.githubusercontent.com/37185368/147803392-9e84eadb-6b48-4824-ae0a-77c4c59ce8ce.jpg)

**Comment by ILIYANGERMANOV** [comment]
Great finding @swapnilkadlag! Feel free to submit us a PR :)

**Comment by ILIYANGERMANOV** [comment]
Closed by @swapnilkadlag thanks to his contribution! :rocket:
