### ISSUE TITLE
[BUG] The timestamp is broken

### ISSUE THREAD

**Issue by Bt2001** [ILIYANGERMANOV/ivy-wallet#357]
The date of transaction will automatically be set on the next day and it's frustrating. I'm from Taiwan does it possibly have something to do with different timezones?
(Sorry for my broken English)

![Screenshot_20220102-001843_Ivy Wallet.jpg](https://user-images.githubusercontent.com/96950275/147855073-4275b73c-22ad-4c0c-97ff-dbd95a3b9dba.jpg)
![Screenshot_20220102-001847_Ivy Wallet.jpg](https://user-images.githubusercontent.com/96950275/147855076-12e6a1b1-5548-476a-9157-a21e0c67a70c.jpg)
![Screenshot_20220102-001857_Ivy Wallet.jpg](https://user-images.githubusercontent.com/96950275/147855080-8ee2ecc7-5cf3-47b9-a4ca-032165fdcb95.jpg)

 - Device: Samsung Galaxy S21
 - OS: Android 11

**Comment by ILIYANGERMANOV** [comment]
Hi @Bt2001 it's timezones. We'll fix that in the furure updates.

**Comment by Vishwa-Raghavendra** [comment]
I'm on it
