### ISSUE TITLE
Setup Ivy Wallet Wiki (help center)

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [ILIYANGERMANOV/ivy-wallet#39]
Create a Github Wiki for the repo where Ivy users can learn more about the product and get answers to FAQ.
- include "Help Center" button in the app's Quick access in more menu

**Comment by snowboulder** [comment]
@ILIYANGERMANOV  I noticed that the help center and FAQs is incomplete. I want to help on documentation. Should I submit a ticket or re-open this one?
