### ISSUE TITLE
[BUG] Start date of month != 1 is broken for January because of wrong year

### ISSUE THREAD

**Issue by ivywallet** [ILIYANGERMANOV/ivy-wallet#400]

**Comment by husseinaltaaf** [comment]
In detail:
My start date of the month ia 29
So in december it was correctly showing Nov 29 2021 - Dec 28 2021
But now in January shouldn't it be Dec 29 2021 - Jan 18 2022 instead i think its showing for 2022 - 2023 because my transaction list is empty since i have some transactions on 1th-5th Jan

**Comment by husseinaltaaf** [comment]
1 more bug is (29 ... - 28 ...) for all month except Feb & march shows 27
For e.g
Jan 29 - Feb 27 instead of Feb 28
Feb 28 - Mar 27 instead of Mar 28

**Comment by ILIYANGERMANOV** [comment]
Steps to reproduce:
1. Select start date of month 28
2. Select January 

Observe: Transactions in January won't be visible. 

@Vishwa-Raghavendra I'm having trouble with this one. Can you check it out? :)

**Comment by Vishwa-Raghavendra** [comment]
I'm on it
