### ISSUE TITLE
Support Light Mode

### ISSUE THREAD

**Issue by ivywallet** [ILIYANGERMANOV/ivy-wallet#42]
Dark mode is beautiful but it would be great to show some loves for light mode.

**Comment by ILIYANGERMANOV** [comment]
Hi, we already support Light mode. To change from Dark to Light mode click the moon button saying "Dark Mode". See screenshot below:
![Screenshot_20211107-184125_Ivy Wallet](https://user-images.githubusercontent.com/5564499/140653813-e4c2cc99-0c6b-4b59-9897-de225b7db463.jpg)
