### ISSUE TITLE
Add "Project Contributors" button in Settings screen

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [ILIYANGERMANOV/ivy-wallet#48]
Add "Contributors" button below "Contact support" in Settings which opens https://github.com/ILIYANGERMANOV/ivy-wallet/graphs/contributors so we can **honor our Ivy Contributors.**

**Comment by timmyCoder** [comment]
I'm on it

**Comment by ILIYANGERMANOV** [comment]
Awesome @timmyCoder! Please use this icon for the button, in size "m"
![Screenshot_20211107-214130_Ivy Wallet](https://user-images.githubusercontent.com/5564499/140659485-01d26bf8-e331-4cf6-9e39-abe664701221.jpg)

**Comment by timmyCoder** [comment]
okay
