### ISSUE TITLE
Helping App Translation

### ISSUE THREAD

**Issue by stepersano** [ILIYANGERMANOV/ivy-wallet#492]
Hi, I am an Italian user that find your app really good... I wanted to contribute to the translation of the app in Italian. How can I do it? 
Thank you! Have a good day.
Greate App!! Bravo!

**Comment by ILIYANGERMANOV** [comment]
Thank you @stepersano! We'll start work on translations after the Graphs & Charts feature. I'll ping you when our localization code is ready so you can help us with Italian. Your help is much appreciated  :)

**Comment by ayesse** [comment]
I'd like to contribute with italian translation as well, if needed :)

**Comment by ILIYANGERMANOV** [comment]
You guys and girls are awesome! I'll do my best to setup community Telegram group and organization so you can collaborate and make a great open-source and free product!

Yes, we'll make the app free and setup donations to a development fund :)

**Comment by StarHamster** [comment]
Duplicate of #342

@stepersano and @ayesse, here is [a link to the mentioned Telegram Community](https://t.me/+ETavgioAvWg4NThk). Maybe one day there will be news about the possibility of translation
