### ISSUE TITLE
Planned Payments/Loans Backup & Restore

### ISSUE THREAD

**Issue by Soukyuu** [ILIYANGERMANOV/ivy-wallet#521]
**What do you want to be added or improved?**
Planned payments and loans are not part of the CSV export - I would like them to be.

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
- [ ] Yes, it already exists.
- [x] No, it's a new issue.
- [ ] I'm not sure but I've checked.

**Explain with bullets why do you need it**
- I don't want to upload my data to Google (yes, my phone is cut off from most Google services)
- I don't want to root my device, so no way to access and transfer private app data

**Explain how do you imagine it in detail**
Write any implementation details that might help us better fulfill your feature request.
**I'd like to:**
- simplest implementation would probably be a separate CSV export
- bonus would be an archive of all CSVs that can be ex- and imported between devices

**Comment by Vishwa-Raghavendra** [comment]
Only Transactions are being exported as of now hence planned payments , loans , budgets  aren't exported 

+1 for this Bug

**Comment by ILIYANGERMANOV** [comment]
Hi @Vishwa-Raghavendra as you prefer, so far your decisions are exactly on point! Soon, I'll release the accumulated changes on `develop`
