### ISSUE TITLE
[BUG] Broken Amount Calculation

### ISSUE THREAD

**Issue by Vishwa-Raghavendra** [ILIYANGERMANOV/ivy-wallet#530]
**Describe the bug**
The app isn't able to calculate the final amount correctly 

**To Reproduce**
1. Add an transaction of 1000 in Default Cash Account 

**Expected Behaviour**
The App should show -1000 as the final result

**Screenshots**
![Broken Amout Calcuation](https://user-images.githubusercontent.com/42895647/154120295-618386dd-fa68-4911-8ac4-f822948c6585.jpeg)

**Smartphone (please complete the following information):**
 - Device: [Redmi note 7 pro]
 - OS: [e.g. Android 10]

**Additional context**

**Comment by marsavela** [comment]
If #531 fixed this, maybe it can be closed. (Y)
