### ISSUE TITLE
Auto Dark Theme

### ISSUE THREAD

**Issue by ivywallet** [ILIYANGERMANOV/ivy-wallet#532]

**Comment by MohitMandalia** [comment]
same as #602 @ILIYANGERMANOV

**Comment by ILIYANGERMANOV** [comment]
Hi @MohitMandalia, can you share your LinkedIn profile with me? I want to gift you Ivy Wallet Lifetime access code :)

**Comment by MohitMandalia** [comment]
> Hi @MohitMandalia, can you share your LinkedIn profile with me? I want to gift you Ivy Wallet Lifetime access code :)

Hi @ILIYANGERMANOV ,

Thanks that is very nice of you.
Here is my id : https://www.linkedin.com/in/mohit-mandalia

Also if you get some time please check my PR for the theme issue #602.
