### ISSUE TITLE
Scan SMS to Get Bank Transactions 

### ISSUE THREAD

**Issue by ivywallet** [ILIYANGERMANOV/ivy-wallet#568]

**Comment by MohitMandalia** [comment]
same as #351 @ILIYANGERMANOV

**Comment by ILIYANGERMANOV** [comment]
Thank you for the help cleaning the issue @MohitMandalia! Much appreciated 🏅

**Comment by MohitMandalia** [comment]
Happy to help improve the app I use in any ways :)
