### ISSUE TITLE
[BUG] Status bar icon color is white in light mode

### ISSUE THREAD

**Issue by Anonym777** [ILIYANGERMANOV/ivy-wallet#574]
Bug description:
The icon colour in the status bar is white and it makes it impossible to see information in the status bar. The issue occurs only in light mode.

1. Go to Home.
2. Click on the drop-down button right of the calendar button.
3. Under 'Quick access' enable Light mode.
4. Close the app.
5. Open the app.
6. See the issue in the status bar.

Expected behavior
The icon colour in the status bar should be dark grey/black when in light mode.

Screenshots
[Screenshot_20220306-192546.jpg](https://user-images.githubusercontent.com/48409258/156930342-9e648f0a-bf8b-4785-9749-92393cbb5623.jpg)

 - Device: OnePlus 7T pro
 - OS: Android 11

Additional information (Edit):
When I navigate to another page which forces the Status bar colour to change, say for example when viewing one of my accounts which has a blue colour, and when i navigate back to the Home screen in the app, the icons in the status bar appear how they are supposed to i.e. dark grey. But then when go to the phone's Home screen i.e. the phone's launcher and then navigate back to the app via the recent apps, the icons appear white again.

**Comment by edsnchz** [comment]
I had the same problem initially on my POCO F3. But it was related to the phone's own dark theme when applied to third-party apps. I just excluded "Ivy wallet" from the list and it fixed

**Comment by Anonym777** [comment]
> I had the same problem initially on my POCO F3. But it was related to the phone's own dark theme when applied to third-party apps. I just excluded "Ivy wallet" from the list and it fixed

Thanks for the reply @edsnchz. But I'm not sure it's the same issue as what you had. In dark mode the status bar icons appear fine for me. The problem is only in light mode.
Anyways, i checked, Ivy Wallet is already excluded from the third-party apps list for the phone's dark theme.

**Comment by Anonym777** [comment]
I noticed something else. I added it under 'Additional information' in the issue's description.

**Comment by Anonym777** [comment]
Hello, while using the app in light mode the status bar colouring issue is fixed now. Not sure how and when, I just noticed it today.
Anyways, thanks for the work on the app guys and the Auto dark theme feature is a nice addition.
