### ISSUE TITLE
Request for Subcategories

### ISSUE THREAD

**Issue by ecoholic84** [ILIYANGERMANOV/ivy-wallet#604]
For example, for adding 'recharge' to expenses, Wouldn't it be cool if there's sub categories for 'recharge'?

(lets take user(x) and user(y) for example)

Expense >> Inputting amount with selecting which wallet >> Selecting 'Recharge' as category >> Choosing one name from the subcategory >> user(x).

This way it would be useful to review the monthly/yearly expenses from the Expenses tab.

**Comment by MohitMandalia** [comment]
could be same as #7 @ILIYANGERMANOV
