### ISSUE TITLE
[BUG] Wrong Account Balance

### ISSUE THREAD

**Issue by Vishwa-Raghavendra** [ILIYANGERMANOV/ivy-wallet#616]
**Describe the bug**
The account balance is wrongly displayed when clicked on an amount

**To Reproduce**
1. Add transactions  to an account ( if the account is newly created make sure to adjust the time for "Adjust Balance transaction" to one month before)
2. Go to Accounts Tab
3. See Balance

**Expected behavior**
Total Account balance should be displayed but it is instead showing present days balance

**Screenshots**

![Initial Image ](https://user-images.githubusercontent.com/42895647/159069632-159d85e3-1e2b-4443-8932-3535a1917d9a.jpeg)

![ Invalid Account](https://user-images.githubusercontent.com/42895647/159069724-1faedd33-6b69-43d2-8b55-c78a7c878b2d.jpeg)

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy S20 Ultra]
 - OS: [e.g. Android 11]

**Additional context**

**Comment by GovindKrishnan** [comment]
If fixed, this can be closed now.
