### ISSUE TITLE
Optimize home screen performance by replacing the fancy animation with simple scrolling

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [ILIYANGERMANOV/ivy-wallet#62]
**What do you want to be added or improved?**
As a user I want home screen's transaction scrolling to be more smooth on weaker devices.

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
No

**Explain with bullets why do you need it**
- make my UX smoother

**Explain how do you imagine it in detail**
Write any implementation details that might help us better fulfill your feature request.
As a user I want to:
- not see lagging wheb scrolling between transactions 
- the hide balance animation can be optimized

**Comment by Vishwa-Raghavendra** [comment]
I am on it

**Comment by ILIYANGERMANOV** [comment]
Closed thanks to @Vishwa-Raghavendra and his awesome PR #170!
