### ISSUE TITLE
Import CSV from Fortune City A Finance App

### ISSUE THREAD

**Issue by Zewar-G** [ILIYANGERMANOV/ivy-wallet#69]
Add support for importing CSV from https://play.google.com/store/apps/details?id=com.fourdesire.fortunecity

It is a famous finance app and supporting it would give Ivy new users a chance to transfer their old data and back ups and start tracking their spendings with Ivy
I've attached an empty copy of the CSV file of the app.

[Fortunecity-records 2.csv](https://github.com/ILIYANGERMANOV/ivy-wallet/files/7503468/Fortunecity-records.2.csv)

**Comment by ILIYANGERMANOV** [comment]
Hi @Zewar-G thank you for raising this ticket and a CSV! We'll include this in our next release. Is it possible to attach a CSV with some sample records (Expense, Income, Transfer) in it?

Mapping:
- columns is 50%
- value is the rest 50% because w/o having actual test date especially for date formats imports are nearly impossible

**Comment by Zewar-G** [comment]
> Hi @Zewar-G thank you for raising this ticket and a CSV! We'll include this in our next release. **Can you to attach a CSV with some sample records (Expense, Income, Transfer) in it?**
> 
> Mapping:
> 
> * columns is 50%
> * value is the rest 50% because w/o having actual test data (especially for date & time formats) imports are nearly impossible

Here is a small version, Sure hope it helps, can't wait to be able to transfer my data and start using Ivy :D
[Fortunecity-records.csv](https://github.com/ILIYANGERMANOV/ivy-wallet/files/7505992/Fortunecity-records.csv)

**Comment by ILIYANGERMANOV** [comment]
Hi @Zewar-G I'm glad to here that! You'll be able to transfer your data in Ivy in our release this, Thursday. This issue will be certainly implemented in it!

**Comment by timmyCoder** [comment]
i'm on it

**Comment by ILIYANGERMANOV** [comment]
Hi @Zewar-G thanks to @timmyCoder's contribution we've released a new Ivy Wallet update containing import CSV from Fortune City feature. It's currently being reviewed by Google and it'll be probably available to you by the end of the day. Test it out and let us know how it has worked out :)
