### ISSUE TITLE
[BUG] income and expenses are set as 0 in the main screen

### ISSUE THREAD

**Issue by Zewar-G** [ILIYANGERMANOV/ivy-wallet#713]
**Describe the bug**
I'm the main screen the expenses and income files are shown as 0, the only way to check the balance is to go to accounts or to show all-time expenses or all-time income 

**To Reproduce**
1. Go to 'main screen'
2. See error

**Expected behavior**
The numbers shall add up and show in the main screen.

**Screenshots**
![IMG_20220412_124436](https://user-images.githubusercontent.com/93976248/162932528-09045fa8-058c-459e-ac5f-4a7fdedd9896.jpg)

**Smartphone (please complete the following information):**
 - Device: Sony Xperia XZ premium
 - OS: Android 12L

**Comment by ILIYANGERMANOV** [comment]
Hi @Zewar-G, thanks for reporting! Is your Cash account excluded from balance?

**Comment by Zewar-G** [comment]
Yes it was excluded, i have included it and now the statements are shown correctly ! Thanks 🙏
