### ISSUE TITLE
Feature to set Planned Account Transfers.

### ISSUE THREAD

**Issue by ivywallet** [ILIYANGERMANOV/ivy-wallet#829]

**Comment by shahiljain** [comment]
I was just going to make a request for this ... Thanks!

**Comment by Jai-mTm** [comment]
+1

**Comment by husseinaltaaf** [comment]
+1

**Comment by husseinaltaaf** [comment]
This feature has been requested by many of us, users... since very long time ago. I don't know why the developers isn't considering this feature as urgent or something like that!

**Comment by Sumat2222** [comment]
+1 please

**Comment by StarHamster** [comment]
Duplicate of #173
