### ISSUE TITLE
Option for save multiple filters for next time [FEATURES] ...

### ISSUE THREAD

**Issue by jdwarraich** [ILIYANGERMANOV/ivy-wallet#891]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to have presets filter that i can edit or add a new one

### Why do you need it?

-  Every time i go to see reports ,i have to selects all filters/option again and again

**Comment by StarHamster** [comment]
Duplicate of #891

**Comment by StarHamster** [comment]
Duplicate of #500
