### ISSUE TITLE
Open/Close Edit Transaction amount sheet with swipe

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [ILIYANGERMANOV/ivy-wallet#92]
**What do you want to be added or improved?**
Open/Close Edit Transaction amount sheet with swipe.

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
No

**Explain with bullets why do you need it**
- swag
- better UX

**Explain how do you imagine it in detail**
Write any implementation details that might help us better fulfill your feature request.
As a user I want to:
- swipe up in closed state => open
- swipe down in open state => close
- refer to the attached recording

https://user-images.githubusercontent.com/5564499/141194772-7726811c-2060-4c29-99bd-a497972f8bbf.mp4

**Comment by MohitMandalia** [comment]
This issue seems to be resolved and merged. @ILIYANGERMANOV
