### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by Zewar-G** [ILIYANGERMANOV/ivy-wallet#94]
It would be great if we can search about some items that we registered before, for example: 
If you search for Taxi
You can see how many times you have this entry, how much you spend for that, etc... Each months how many times you have entered it, and over all as well, you can specific the search.

**Comment by ILIYANGERMANOV** [comment]
Hi @Zewar-G thanks for the feedback! Did you try our "Reports" feature? It has really powerful filter, e.g. include keyword even exclude. 

Anyway we'll also add a simple search in future versions:)

**Comment by Zewar-G** [comment]
![Screenshot_20211112-163441_Ivy_Wallet](https://user-images.githubusercontent.com/93976248/141475644-f0424f85-5f7b-469b-85e8-b599abcf76cd.png)
I got an idea maybe we can add this function to this menu here at the bottom or the top as an icon
