### ISSUE TITLE
[BUG] ... No data is showing in month view

### ISSUE THREAD

**Issue by Zewar-G** [ILIYANGERMANOV/ivy-wallet#95]
Nothing is showing up on the main screen when choosing one month ,only it's shown when you pick all_time.

Screenshots:
All time record
![InShot_20211111_021852417](https://user-images.githubusercontent.com/93976248/141209133-1032aa69-9efa-499f-a0bf-e173438bd367.jpg)
One month record
![InShot_20211111_022035195](https://user-images.githubusercontent.com/93976248/141209257-156032ca-63f0-41e4-8262-1fdfa4d79902.jpg)

Smartphone:
 - Device: [Sony Xperia XZ premium]
 - OS: [Android 11]

**Comment by ILIYANGERMANOV** [comment]
Hi @Zewar-G thanks for reporting! I think what's happening is that you've imported your data, am I right?

It couldn't parse the date of your imported transactions so it sets a default date today.minusYears(1) => that's November 2020.

**From which apl did you import your data? And can you send me CSV sample? I need their exact date format.**

**Comment by ILIYANGERMANOV** [comment]
@Zewar-G nvm, I found the CSV you sent us as a sample. I have all the data I need. I'll fix it tomorrow. Thanks for reporting again!
