### ISSUE TITLE
[FEATURES] Skip All Overdue Planned Payments

### ISSUE THREAD

**Issue by jevo160296** [ILIYANGERMANOV/ivy-wallet#962]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to be able to skip all overdue planned payments with one clic.

### Why do you need it?

- I'll have the opportunity to focus only on the payments I made, and close all the ones I didn't confirm payment.

### How do you imagine it?

There´s a button in the overdue payments list.
I clic that button
A confirmation dialog pops up asking for confirmation
I confirm the skip action
All the overdue payments are skipped.

**Comment by jevo160296** [comment]
I'm working on it

**Comment by ILIYANGERMANOV** [comment]
Awesome @jevo160296! That's a cool feature 🚀
