### ISSUE TITLE
Display transaction's year if it isn't in the current year

### ISSUE THREAD

**Issue by ILIYANGERMANOV** [ILIYANGERMANOV/ivy-wallet#97]
**What do you want to be added or improved?**
Show November, 2020 for transactions if now we are 2021.

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
No

**Explain with bullets why do you need it**
- #93 
- #95 

**Explain how do you imagine it in detail**
Write any implementation details that might help us better fulfill your feature request.
As a user I want to:
- See year in transaction's date divider if it's not in current year
- Same applies for due dates
- Same for transaction's dateTime

**Comment by Zewar-G** [comment]
Shall I delete my data and try again now ?

**Comment by ILIYANGERMANOV** [comment]
@Zewar-G yes, please do so. But first check that you have latest version from the PlayStore.

**Comment by Zewar-G** [comment]
> @Zewar-G yes, please do so. But first check that you have latest version from the PlayStore.

Unfortunately the same problem still exist
I got this version version 2.2.0-comet

**Comment by Zewar-G** [comment]
Even when I choose from the beginning of November until today I don't get any of the results,
![Screenshot_20211111-193518_Ivy_Wallet](https://user-images.githubusercontent.com/93976248/141334706-fdc63ddd-cd44-46c1-b9da-79ab5ea9bb72.png)
And all of the entries that I imported or under the date of today and the same hour that I entered all of them

**Comment by ILIYANGERMANOV** [comment]
@Zewar-G fck xD This Fortune City CSV dates are awful... I managed to import 100% of the sample that you've send me. Will investigate further!

**Comment by Zewar-G** [comment]
Please let me know if I can do anything, by the way is it okey to contact you via telegram?

**Comment by ILIYANGERMANOV** [comment]
@Zewar-G can you send me only date column for all of your transactions because this way I can analyze it and map all formats this stupid CSV use 😅

About Telegram I don't use it often but feel free to drop me a line to https://t.me/iliyangermanov.

If a lot of people prefer Telegram for chatting we can also create an Ivy Wallet community group there.

**Comment by Zewar-G** [comment]
Sure I'll send it, and yes it's easier to get in contact with the community this way !
